name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    name: "Spellcheck"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade codespell
      - name: Run spellcheck
        run: |
          codespell $(git ls-files)
  prettier:
    runs-on: ubuntu-latest
    name: "Prettier"
    steps:
      - uses: actions/checkout@v3
      - uses: creyD/prettier_action@v4.3
        with:
          prettier_options: "--check **/*.md"
          dry: true
